#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Sets up Cloudflare Pages deploys for .github/workflows/ci.yml: the secrets
# CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID, and the repo variable
# CLOUDFLARE_PAGES_PROJECT (the deploy job is skipped until it's set).
# Run from anywhere: ./scripts/setup-cloudflare.sh

cd "$(dirname "$0")/.."

TOTAL_STAGES=6

banner "Cloudflare Pages deploy setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check your tools"
say "This wizard saves GitHub secrets with the gh CLI and creates the Pages"
say "project with Cloudflare's wrangler CLI (run through npx)."
until command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; do
  warn "gh isn't installed or isn't signed in."
  step "Install it (https://cli.github.com), then run: gh auth login"
  pause "Press Enter when gh is ready (Ctrl-C to stop)"
done
REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
printf '  %s✓%s gh is signed in; secrets will go to %s\n' "$GREEN" "$RESET" "$REPO"
until command -v npx >/dev/null 2>&1; do
  warn "npx isn't available. Install Node (see .nvmrc), e.g. with: nvm install"
  pause "Press Enter when Node is installed (Ctrl-C to stop)"
done
printf '  %s✓%s npx is available\n' "$GREEN" "$RESET"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare account"
say "The site is hosted on Cloudflare Pages (free plan). Sign in to your"
say "Cloudflare account, or create one."
open_url "https://dash.cloudflare.com/login"
step "Sign in, or choose 'Sign up' and create a free account."
step "Once you're in the dashboard, look at the address bar: the URL looks like"
note "    https://dash.cloudflare.com/<account ID>/home"
step "Copy the account ID: the 32-character code after dash.cloudflare.com/."
note "(It's also on Workers & Pages → Overview, under 'Account details'.)"
while true; do
  ask CLOUDFLARE_ACCOUNT_ID "Paste the account ID:"
  [[ "$CLOUDFLARE_ACCOUNT_ID" =~ ^[0-9a-f]{32}$ ]] && break
  warn "That doesn't look like an account ID (32 characters, 0-9 and a-f)."
done
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the Pages project"
say "CI uploads the built site itself (Direct Upload), so tests gate every"
say "deploy. Don't connect the project to GitHub in Cloudflare."
say "The project name becomes the site address: <name>.pages.dev"
note "Lowercase letters, numbers and dashes, e.g. formula-concentration."
while true; do
  ask CLOUDFLARE_PAGES_PROJECT "Project name:"
  [[ "$CLOUDFLARE_PAGES_PROJECT" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] && break
  warn "Use lowercase letters, numbers and dashes (not at the start or end)."
done
write_env CLOUDFLARE_PAGES_PROJECT "$CLOUDFLARE_PAGES_PROJECT"
if confirm "Create '$CLOUDFLARE_PAGES_PROJECT' now with wrangler? (skip if it already exists)"; then
  say "wrangler may open your browser to sign in to Cloudflare; allow access."
  export CLOUDFLARE_ACCOUNT_ID
  if npx -y wrangler@4 pages project create "$CLOUDFLARE_PAGES_PROJECT" --production-branch=main; then
    printf '  %s✓ created%s Pages project %s\n' "$GREEN" "$RESET" "$CLOUDFLARE_PAGES_PROJECT"
    note "Note the pages.dev address wrangler printed above. Cloudflare adds a"
    note "suffix if the name was taken."
  else
    warn "wrangler couldn't create the project (see the output above)."
    SKIPPED+=("Create the Pages project '$CLOUDFLARE_PAGES_PROJECT' (Direct Upload, production branch main)")
  fi
else
  note "Skipped. The project must exist as a Direct Upload project whose"
  note "production branch is 'main', or every deploy will be a preview."
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create an API token for CI"
say "CI needs a token that can deploy to Pages and nothing else."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Click 'Create Token', then 'Get started' next to 'Create Custom Token'."
step "Token name: GitHub Actions ($REPO)"
step "Permissions: Account  ·  Cloudflare Pages  ·  Edit"
step "Account Resources: Include  ·  your account"
step "Click 'Continue to summary', then 'Create Token'."
step "Copy the token. Cloudflare shows it only once."
note "The token isn't saved in .env; it only goes to GitHub."
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token (hidden):"
while [[ -z "$CLOUDFLARE_API_TOKEN" ]]; do
  warn "No token entered."
  ask_secret CLOUDFLARE_API_TOKEN "Paste the API token (hidden):"
done
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Save to GitHub"
say "These go to $REPO:"
step "secret    CLOUDFLARE_API_TOKEN"
step "secret    CLOUDFLARE_ACCOUNT_ID = $CLOUDFLARE_ACCOUNT_ID"
step "variable  CLOUDFLARE_PAGES_PROJECT = $CLOUDFLARE_PAGES_PROJECT"
note "Setting the variable turns on the deploy job in CI."
if confirm "Save them now? (overwrites existing values)"; then
  set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
  set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
  set_var CLOUDFLARE_PAGES_PROJECT "$CLOUDFLARE_PAGES_PROJECT"
else
  SKIPPED+=("gh secret set CLOUDFLARE_API_TOKEN")
  SKIPPED+=("gh secret set CLOUDFLARE_ACCOUNT_ID --body $CLOUDFLARE_ACCOUNT_ID")
  SKIPPED+=("gh variable set CLOUDFLARE_PAGES_PROJECT --body $CLOUDFLARE_PAGES_PROJECT")
fi
unset CLOUDFLARE_API_TOKEN
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "First production deploy"
say "Every push to main now deploys to production, and every PR gets a"
say "preview. To deploy what's on main right now, start the CI workflow."
if confirm "Run CI on main now?"; then
  if gh workflow run ci.yml --ref main; then
    printf '  %s✓ started%s CI on main\n' "$GREEN" "$RESET"
    open_url "https://github.com/$REPO/actions/workflows/ci.yml"
    step "Wait for 'Deploy to Cloudflare Pages' to finish; its summary shows the URL."
  else
    warn "Couldn't start CI (is the deploy workflow merged to main yet?)."
    SKIPPED+=("First deploy: gh workflow run ci.yml --ref main")
  fi
else
  SKIPPED+=("First deploy: gh workflow run ci.yml --ref main (or push to main)")
fi
note "The site will be at https://$CLOUDFLARE_PAGES_PROJECT.pages.dev (plus any"
note "suffix Cloudflare added)."
pause

finish
